// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © dvaduva
strategy(overlay=false, shorttitle="N MACD + RSI14 + SMA50", default_qty_type = strategy.percent_of_equity, initial_capital = 10000, default_qty_value = 100, pyramiding = 0, title="Normalized MACD + RSI14 + SMA50", currency = 'USD')

sma = input(12,title='Fast MA')
lma = input(21,title='Slow MA')
tsp = input(9,title='Trigger')
np = input(50,title='Normalize')
h=input(true,title='Histogram')
multiple = 20
docol = input(false,title="Color Change")
dofill=input(false,title="Fill")
type = input(1,minval=1,maxval=3,title="1=Ema, 2=Wma, 3=Sma")

sh = type == 1 ? ema(close,sma)  
 : type == 2 ? wma(close, sma)
 : sma(close, sma)

lon=type == 1 ? ema(close,lma) 
 : type == 2 ? wma(close, lma)
 : sma(close, lma)

ratio = min(sh,lon)/max(sh,lon)
Mac = (iff(sh>lon,2-ratio,ratio)-1)
MacNorm = ((Mac-lowest(Mac, np)) /(highest(Mac, np)-lowest(Mac, np)+.000001)*2)- 1
MacNorm2 = iff(np<2,Mac,MacNorm)
Trigger = wma(MacNorm2, tsp)
Hist = (MacNorm2-Trigger)
Hist2 = Hist>1?1:Hist<-1?-1:Hist
swap=Hist2>Hist2[1]?green:red
swap2 = docol ? MacNorm2 > MacNorm2[1] ? #0094FF : #FF006E : red
plot(h?multiple*Hist2:na,color=swap,style=columns,title='Hist',histbase=0)
plot(multiple*MacNorm2,color=swap2,linewidth=2,title='MacNorm')
plot(multiple*dofill?MacNorm2:na,color=MacNorm2>0?green:red,style=columns)
plot(multiple*Trigger,color=black,linewidth=2,title='Trigger')
hline(0)

//rsi
swr=input(true,title="RSI")
src = close, len = input(14, minval=1, title="Length RSI")
srs = input(50, minval=1, title="Length sma RSI")
up = rma(max(change(src), 0), len)
down = rma(-min(change(src), 0), len)
rsi = down == 0 ? 100 : up == 0 ? 0 : 100 - (100 / (1 + up / down))
mr=sma(rsi,srs)
plot(swr?rsi:na,title="RSI", color=purple,transp=0)
plot(swr?mr:na,title="Sma RSI", color=red,transp=0)

macdOver  = crossover(MacNorm2,Trigger)
macdUnder = crossunder(MacNorm2,Trigger)
rsiOver   = crossover(up,down)
rsiUnder  = crossover(up,down)

plot(macdOver  ?  10:na , color=green, linewidth=5, offset=0, style = histogram, transp=50)
plot(macdUnder ? -10:na , color=red,   linewidth=5, offset=0, style = histogram, transp=50)

////stragegy
//longFilter = crossover(MacNorm2,Trigger)
//plotchar(longFilter,  title="SELL", char="S", location=location.abovebar)
